plugins:
  - jekyll-remote-theme

title: Negshell Casting
baseurl:
remote_theme: pmarsceill/just-the-docs
description: 'Negshell casting: 3D-printed structured and sacrificial cores for soft robot fabrication companion documentation'
aux_links:
  'Read the Full Paper':
    - "//journals.plos.org/plosone/article?id=10.1371/journal.pone.0234354"
footer_content: 'If you found this guide helpful, please cite the paper and/or this website. ♥ <br /> <a href="https://prnthp.github.io">Jom Preechayasomboon</a>, 2020'
ga_tracking: G-DL8LXSXYHG
